### ISSUE TITLE
Make a cabal 3.2 compatible release

### ISSUE THREAD

**Issue by maralorn** [phadej/cabal-fmt#17]
Commit 3001781a268fa3691b674aac01c255b10a0468a6 introduced a fix, which is necessary to build `cabal-fmt` on nixos-unstable.

If you make a new release we can mark `cabal-fmt` unbroken in nixpkgs.

Sorry to bother you about this. But having a Cabal 3.2 compatible version released is - I think - a better option than overriding the source in nixpkgs.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cabal-fmt-0.1.3
