### ISSUE TITLE
Multiple `build-depends` fields

### ISSUE THREAD

**Issue by nomeata** [phadej/cabal-fmt#23]
This might not be well known, so I thought I’d point it out: 

Instead of
```
  build-depends:
    , base        >=4.11 && <4.13
    , bytestring
    , Cabal       ^>=2.5
    , containers  ^>=0.5.11.0 || ^>=0.6.0.1
    , pretty      ^>=1.1.3.6
```
you can also write
```
  build-depends: base        >=4.11 && <4.13
  build-depends: bytestring
  build-depends: Cabal       ^>=2.5
  build-depends: containers  ^>=0.5.11.0 || ^>=0.6.0.1
  build-depends: pretty      ^>=1.1.3.6
```
which doesn’t need odd leading commas, and is very diff friendly. I use it in all my projects…

Just a suggestion, I am not even actually using your tool (yet) :-)

Feel free to close this if you don’t like it

**Comment by phadej** [comment]
One could argue that this should be done for every comma separated field, which are not many:
- `build-depends`
- `build-tool-depends`
- `pkgconfig-depends`
- `mixins`
- `reexported-modules` (because of renaming, i.e. `Foo as Bar` we require commas)

I'm not opposed, (configurable) patch is welcome.

**Comment by phadej** [comment]
Another problem: when pretty-printing the AST, each individual field is formatted separately.

In other words, when there is *one, big `build-depends`*, we can have tabular output.
With separate `build-depends`, we cannot.

I'm not convinced that complication is worthwhile.

More concretely, splitting single `build-depends` into separate `build-depends` is possible and could be done.
For tabular formatting (which I assume is implied as nice-to-have property) I'd like to see how someone would implement that.

**Comment by nomeata** [comment]
Fair point, in my cabal files I don’t bother with vertially aligning the version bounds. Probably not worth it then, especially when one is using an automatic formatter.
