### ISSUE TITLE
`expand` should ignore `main-is` file

### ISSUE THREAD

**Issue by bitc** [phadej/cabal-fmt#27]
I am using [hspec](https://hackage.haskell.org/package/hspec)

Following the official example:

https://github.com/hspec/hspec-example/blob/3208caa4548a46c3ab7da030817f0ccbf189c4b8/strip.cabal#L28

This is the relevant section of the cabal file looks like:

```
test-suite spec
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs:
      test
  other-modules:
      Data.String.StripSpec
      Paths_strip
```

When I add `-- cabal-fmt: expand test`, then cabal-fmt adds `Spec` to other-modules, and this breaks the build.

cabal-fmt should notice that `Spec.hs` is already listed in the `main-is` field and so shouldn't add it to `other-modules`

Thank you

**Comment by phadej** [comment]
Use  `expand test -Spec`
