### ISSUE TITLE
Preserving empty lines in free text fields

### ISSUE THREAD

**Issue by jlwoodwa** [phadej/cabal-fmt#29]
cabal-fmt strips empty lines from all fields. However, with the new free text rules (https://github.com/haskell/cabal/pull/5981), empty lines seem to be the only way to break paragraphs in the description field, etc. (Previously, a line containing a single period would do the trick, and cabal-fmt preserved this.)

Can cabal-fmt be changed to preserve empty lines in free text fields?

**Comment by phadej** [comment]
Yes, that would be good to fix.

**Comment by shlevy** [comment]
@phadej Would this be a hard fix? Can you point to where to look?

**Comment by phadej** [comment]
@shlevy I suspect it's an issue in `Cabal-syntax`. See #86 

The `traceShowId` prints `"First Paragraph\nSecond Paragraph", i.e. there is a missing line feed already. 

https://github.com/haskell/cabal/blob/f01e000b92ddf8cf04a175228e0758fafb732a4d/Cabal-syntax/src/Distribution/FieldGrammar/Parsec.hs#L404 is a suspect. It makes the indentation be right, but it forgets to insert empty lines when the are between input `FieldLine`s (i.e. line positions are differ by two or more).

**Comment by phadej** [comment]
Actually no. The issue is in `cabal-fmt`.

**Comment by phadej** [comment]
The #86 seems to work, I'll cleanup it later this month
