### ISSUE TITLE
Reformats `if flag` incorrectly

### ISSUE THREAD

**Issue by srid** [phadej/cabal-fmt#31]
Using 0.1.5.1 on [this cabal file](https://github.com/srid/ema/pull/14/commits/a8e8769d355f07bc4d72f7d6c9f57f99f9ed1417#diff-9812ebcc555d5296505859bb91a93e261ee970df622d4cff97e7442b8703fe69L33-R35)

![image](https://user-images.githubusercontent.com/3998/115898862-0b4c5400-a42c-11eb-881d-56a38e97b5eb.png)

**Comment by phadej** [comment]
It does reformat them correctly. There is no `if` inside the `data-files`. What you originally wrote is three globs:
- `if`
- `flag(with-examples`
- `src/Ema/Example/Diary/*.org`

(which are separated by spaces).

**Comment by srid** [comment]
So `if` is supported only directly inside library/executable stanzas? Okay.
