### ISSUE TITLE
Not compatible with base-4.16

### ISSUE THREAD

**Issue by peacememories** [phadej/cabal-fmt#44]
Hi, thanks for creating this formatter! :)

I just installed Haskell again and wanted to start a project, and while getting my editor set up I noticed that I cannot install `cabal-fmt` with my current Haskell version. the problem seems to be that cabal-fmt does not accept base-4.16.0.0 as a base, which is the one that is installed with my ghc 9.2.1
Is there something I'm missing?

**Comment by kafji** [comment]
Yeah, I can't install it with GHC 9.2 as well.

A workaround is by creating a local copy and bumping the deps (`base` & `bytestring`).

```
-    , base        ^>=4.11.1.0 || ^>=4.12.0.0 || ^>=4.13.0.0 || ^>=4.14.0.0
-    , bytestring  ^>=0.10.8.2
+    , base        ^>=4.11.1.0 || ^>=4.12.0.0 || ^>=4.13.0.0 || ^>=4.14.0.0 || ^>=4.16.0.0
+    , bytestring  ^>=0.11.3.0
```

**Comment by phadej** [comment]
Done in #58
