### ISSUE TITLE
`cabal-fmt` removes libraries when using `:` notation

### ISSUE THREAD

**Issue by MangoIV** [phadej/cabal-fmt#54]
I have a `.cabal` file with a line like `lib:{lib,gen}` and `cabal-fmt` rewrites that to `lib`. Is this behaviour documented somewhere (or is it unexpected)? 

(version is `0.1.5.1`)

Thanks in advance!

**Comment by phadej** [comment]
It's fixed in #45  but I guess I haven't yet made a release?

**Comment by MangoIV** [comment]
Thank you, yes, a release with the change would be nice. 
Please excuse the worries.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/cabal-fmt-0.1.6 is on Hackage

**Comment by MangoIV** [comment]
awesome, thank you!
