### ISSUE TITLE
Use cabal-fmt as a cabal-modifier?

### ISSUE THREAD

**Issue by nomeata** [phadej/cabal-fmt#64]
I’d like to write tools that edit my cabal file in place, and `cabal-fmt` seems to be the most suitable starting point. But all the interesting code seems to be in the internal `cabal-fmt-internal` sublibrary, so I cannot easily extend it.

Do you plan to make the this functionality available for extension?

Or, alternative, what’s your advise for a cabal-modifying tool?

**Comment by phadej** [comment]
> Do you plan to make the this functionality available for extension?

No

> Or, alternative, what’s your advise for a cabal-modifying tool?

Idk

**Comment by phadej** [comment]
> Or, alternative, what’s your advise for a cabal-modifying tool?

... or ping people on https://github.com/haskell/cabal/issues/7337 or https://github.com/haskell/cabal/projects/9

**Comment by nomeata** [comment]
Ok, thanks :-)

I guess since I only have to change the value of existing fields, for my initial experiments I can use the `Cabal-syntax` parser to get fields with source positions, calculate the new values, and then splice them into the original source.
