### ISSUE TITLE
`cabal-fmt` moves comments inside fields

### ISSUE THREAD

**Issue by michaelpj** [phadej/cabal-fmt#67]
It's common to want to add an explanatory comment giving the reason for a constraint, e.g.
```
build-depends:
   base >= X
   -- foo-Y breaks our code, remove once <issue URL> is fixed
   , foo < Y 
```

Currently `cabal-fmt` moves this comment to above the `build-depends` stanza.

**Comment by phadej** [comment]
Separate specific stuff into separate `build-depends`.

```cabal
build-depends:
   , base >= X

-- foo-Y breaks our code, remove once <issue URL> is fixed
build-depends:
   , foo < Y 
```

**Comment by michaelpj** [comment]
Thanks, that's a good workaround, and I'm inferring from the label that you think it's good enough to not be worth fixing the issue.

**Comment by phadej** [comment]
Trying to preserve an attachment of comment inside things is **difficult**.

```
build-depends:
  foo,
   -- comment about both quu and boo
   quu, boo
 ```
 
 what happens when the list is ordered? I don't want to think about such corner-cases.

**Comment by michaelpj** [comment]
Yes, I think that's very reasonable.
