### ISSUE TITLE
The expand pragma should exclude the entry in `main-is`

### ISSUE THREAD

**Issue by HugoPeters1024** [phadej/cabal-fmt#81]
`cabal-fmt` breaks my tests when using `hspec` with autodiscovery.

I have a `tests/Spec.hs` containing a pragma to discover all other spec files.
In the cabal file I have an entry for the `test-suite` with a `main-is: Spec.hs` entry.
If I put the `-- cabal-ftm: expand tests` pragma above `other-modules` it will also include `Spec` there which causes things to break in surprisingly cryptic ways (but that's not `cabal-fmt` fault).

The solution is to filter out the entry in `main-is`, if any, from the list of modules generated by the expansion.

current `cabal-fmt` result:

```
test-suite: my-tests
main-is: Spec.hs

--cabal-fmt: expand tests
other-modules:
  Endpoint.AmazingTests
  Spec
```

desired `cabal-fmt` result:

```
test-suite: my-tests
main-is: Spec.hs

--cabal-fmt: expand tests
other-modules:
  Endpoint.AmazingTests
```

**Comment by HugoPeters1024** [comment]
A possible workaround was shown to me:

```
-- cabal-fmt: expand tests -Spec
```

**Comment by phadej** [comment]
Another workaround is too name the file in lower case (or somehow that it's not a valid module name): `main-is: spec.hs`, then expansion won't pick up it as it's not a valid module name (works on case sensitive file systems).

The expansion of individual fields won't take into account the other contents (so for example expansion of `other-modules` won't take into account `main-is` field). it's a deliberate design choice, and won't change easily. `cabal-fmt` doesn't really know about overall cabal file structure, it just looks at the individual fields one at the time.

**Comment by HugoPeters1024** [comment]
If I understand correctly, my feature request does not align with your design goals and there are suitable workarounds. As such, I'll close this issue.
